language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run lint
- npm run test:unit
- npm run build
deploy:
  provider: script
  script: gae-deploy.sh $TRAVIS_TAG
  on:
    branch: prod
    tag: true
before_install:
- openssl aes-256-cbc -K $encrypted_199e361aa0e1_key -iv $encrypted_199e361aa0e1_iv
  -in .sentryclirc.enc -out .\\.sentryclirc -d
- openssl aes-256-cbc -K $encrypted_199e361aa0e1_key -iv $encrypted_199e361aa0e1_iv
  -in travis-ci-gae-deploy.json.enc -out .\\travis-ci-gae-deploy.json -d
