language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run lint
- npm run test:unit
- npm run build
deploy:
  provider: script
  script: sh ./gae-deploy.sh $TRAVIS_TAG
  skip_cleanup: true
  on:
    tags: true
    branch: prod
before_install:
- openssl aes-256-cbc -K $encrypted_e9464e2524e7_key -iv $encrypted_e9464e2524e7_iv
  -in credentials.tar.enc -out credentials.tar -d
- tar xvf credentials.tar
