language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run lint
- npm run build
deploy:
  provider: script
  script: gae-deploy.sh $TRAVIS_TAG
  on:
    tag: true
    all_branches: true
before_install:
- openssl aes-256-cbc -K $encrypted_e9464e2524e7_key -iv $encrypted_e9464e2524e7_iv
  -in credentials.tar.enc -out credentials.tar -d
- tar xvf credentials.tar
